"""empty message

Revision ID: 1fd9a2265cb3
Revises: 
Create Date: 2025-06-29 17:40:41.297933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd9a2265cb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_column('unit')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.TEXT(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
