"""empty message

Revision ID: 534150f59c76
Revises: 1fd9a2265cb3
Create Date: 2025-06-29 18:35:41.729637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534150f59c76'
down_revision = '1fd9a2265cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
